name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Test
        run: go test -v ./...

      - name: Generate build files
        uses: psethwick/go-cross-build@e7834b3e25f295c657460a48da60b176e459b8cf
        with:
          platforms: linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64
          package: cmd/gex
          ldflags: -s -w
          name: gex
          dest: dist

      - uses: actions/upload-artifact@v2
        with:
          name: gex-linux-amd64
          path: dist/gex-linux-amd64

      - uses: actions/upload-artifact@v2
        with:
          name: gex-linux-arm64
          path: dist/gex-linux-arm64

      - uses: actions/upload-artifact@v2
        with:
          name: gex-darwin-amd64
          path: dist/gex-darwin-amd64

      - uses: actions/upload-artifact@v2
        with:
          name: gex-darwin-arm64
          path: dist/gex-darwin-arm64

      - uses: actions/upload-artifact@v2
        with:
          name: gex-windows-amd64
          path: dist/gex-windows-amd64.exe
